---
framework: mocha
tier: small
postMerge:
  pattern:
    - "./build/test/utils.js"
preMerge:
  pattern:
    - "./build/test/utils.js"
preRun:
     command:
        - npm install
        - npm run compile
postRun:
     command:
        - node --version
version: 1.0
